version: '3.8'

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  scrapy:
    build:
      context: .
      dockerfile: ./ScrapyTennis/Dockerfile
    depends_on:
      - mongo
    # Autres configurations pour Scrapy

  dash:
    build:
      context: .
      dockerfile: ./Dash/Dockerfile
    ports:
      - "8050:8050"
    depends_on:
      - mongo
    # Autres configurations pour Dash

volumes:
  mongodb_data: